### ISSUE TITLE
Characters do not always fit inside the div 

### ISSUE THREAD

**Issue by samysammour** [tossnet/Blazor-Captcha#10]
Thanks for the Package, however, the characters are sometimes not fully displayed and they don't fit in the frame.
I set the number of characters to 5.

Only 4 are displayed instead of 5:
![image](https://user-images.githubusercontent.com/23645279/184350589-eca4720d-3d57-470a-9ed4-9b05cdd3e6ed.png)

The letter x is very hard to read:
![image](https://user-images.githubusercontent.com/23645279/184350645-3d374dee-d8e3-4bd2-9fc6-b06f3ea68c34.png)

**Comment by ChristophSilge** [comment]
I also had the problem. My approach was to rewrite the drawing method.
I struggled a lot with rotation and positioning until I changed the following lines to Captcha.cs >BuildRenderTree
`
canvas.Save();
canvas.Translate(x, y);
canvas.RotateDegrees(l.Angle);
canvas.DrawText(l.Value, x, y, paint);
canvas.Restore();
`
into 
` 
canvas.Save();
canvas.RotateDegrees(l.Angle, x, y);
canvas.DrawText(l.Value, x, y, paint);
canvas.Restore();
`

**Comment by xFlowneox** [comment]
![image](https://github.com/tossnet/Blazor-Captcha/assets/119118450/d8b165c0-bfc4-444e-9d64-8f2c3a0735e1)

i have the same issue on linux, on windows it seems to work as intended, but on linux i selected 7 characters and sometimes i don‘t even get one character shown… as shown in the example above there should also be 7, if i degrade the number it just shows less characters if i degrade it to low it just shows nothing empty box… does anyone know this issue and how to fix it?

I host my blazor app in a linux container btw

**Comment by Andrey-2021** [comment]
Hi!
It's a problem. C# 9

![image](https://github.com/user-attachments/assets/eaf961b6-bbf5-4bc7-8343-648965d5bcbd)
