### ISSUE TITLE
Blazor web assembly  captcha

### ISSUE THREAD

**Issue by PersianCoders** [tossnet/Blazor-Captcha#4]
hello dear,
how can i run captcha in Blazor web assembly?
please help me

thanks

**Comment by tossnet** [comment]
I use system.drawing and it is not compatible with WASM. I have to find a universal solution (like the html5 Canvas...)

**Comment by moehoward** [comment]
In .NET 6 and later versions, the System.Drawing.Common NuGet package is only supported on Windows operating systems. For more information, see System.Drawing.Common only supported on Windows.

https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=net-5.0
