### ISSUE TITLE
Dependent on BootStrap?

### ISSUE THREAD

**Issue by moehoward** [tossnet/Blazor-Captcha#5]
It seems like this component is dependent ("btn") on BootStrap?

    builder.AddAttribute(++seq, "class", "btn btn-refresh");

In other words, it looks like your refresh button needs BootStrap.
Was this your intent?

Nevertheless, this is still a pretty decent component.
I just wish it wasn't dependent on System.Drawing either.

:<)

**Comment by tossnet** [comment]
indeed it is bootstrap. We can separate from it
