### ISSUE TITLE
Potential issue with LINUX deployment

### ISSUE THREAD

**Issue by bjh0** [tossnet/Blazor-Captcha#7]
I implemented this library in my Blazor Server application and it worked perfectly in development on my Windows machine.  But after deployment to my LINUX server the following exception is thrown:

`System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies.`

I checked the dependancies and I saw that there was a requirement for SkiaSharp.NativeAssets which has separate versions for Windows and macOS:

![image](https://user-images.githubusercontent.com/90199620/157513374-97353165-8916-4520-916f-89989c3eef7b.png)

I checked on Nuget and there is actually a LINUX version of SkiaSharp.NativeAssets as well, but it's not included with the Blazor-Captcha package.

So I'm guessing that this explains my deployment problem on LINUX.

**Comment by tossnet** [comment]
I admit I don't know if adding it will solve the problem. It costs nothing to try

**Comment by tossnet** [comment]
I just tried my Blazor app on linux and my component is runing ...🤔 ![image](https://user-images.githubusercontent.com/3845786/157723309-73103d18-f952-4de5-98bf-49d3ba668ecd.png)

**Comment by bjh0** [comment]
Interesting.  I wonder if this is a publishing problem on my end.  It works fine for me in development (although that is on Windows).  The fact that the SkiaSharp.NativeAssets.LINUX package was missing made me suspect that this was the problem.

OK, if you don't mind leaving the issue open for a while next week, I will try to get to the bottom of it.

**Comment by tossnet** [comment]
Maybe your App Service has a Linux OS and not Windows?
Anyway, I updated the Nuget package yesterday with the LINUX library as well. Try it and tell me if adding it works automatically?

**Comment by bjh0** [comment]
I'm not using an App Service on Azure, I'm deploying to a real LINUX server.
OK I will update the package my end and see if this fixes it for me - that's an easy thing for me to try first, thanks for your help.  If it doesn't work I'll try to get to the bottom of it and report back.

**Comment by bjh0** [comment]
So, I updated the package to your latest version.  The only other change I made was to make the captcha optional depending on an appsettings.json entry so that I could switch it off if it didn't work.

But no need to switch it off, because now it's working!

**Comment by Metaln00b** [comment]
Hey, I had some issues running the captcha under a docker container.

There is maybe a package needed which is called `libfontconfig1`.

Add the line `RUN apt-get update && apt-get install -y libfontconfig1` in your `Dockerfile`

e.g.
```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
RUN apt-get update && apt-get install -y libfontconfig1
```

Greetings
